name = "pdomkub-status"
main = "src/worker.ts"
compatibility_date = "2026-09-05"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.png"]
fallthrough = true
