name = "pdomkub-status"
main = "src/worker.ts"
compatibility_date = "2026-09-05"

[assets]
directory = "./src/web"
binding = "ASSETS"
run_worker_first = true

[[routes]]
pattern = "status.kisuru.site/pdomkub"
zone_name = "kisuru.site"

[[routes]]
pattern = "status.kisuru.site/pdomkub/*"
zone_name = "kisuru.site"
